### ISSUE TITLE
Deleting user in OWF deletes all associated ROLEs in database

### ISSUE THREAD

**Issue by rfetters** [ozoneplatform/owf-framework#76] opened 2016-04-12 19:08 UTC
If a user is deleted via the OWF Administration user management interface, the roles associated with that user are also deleted from the ROLE table.  When other user's who have been assigned the role(s) access OWF they receive "An error has occurred on the server" message.

Workaround is to reinsert the ROLE.

**Comment by rpokorny** [comment] 2016-06-28 18:25
I wasn't able to reproduce the issue exactly as you saw it.  For me, I wasn't able to delete users at all due to foreign key constraints being violated.  I have just fixed that so hopefully the issue that you saw will be fixed as well.

**Comment by mparizernc** [comment] 2016-07-11 18:03
Like Ross I was not able to reproduce the issue found by @rfetters but was able to reproduce the issue the same way as @rpokorny.  I have verified that deleting users no longer removes the roles.I have verified this for both users and admins.

**Closed by mparizernc** 2016-07-11 18:03 UTC
