### ISSUE TITLE
Images in externally hosted themes revert to default when requested under /images

### ISSUE THREAD

**Issue by kentbutler** [ozoneplatform/owf-framework#23] opened 2013-07-03 15:57 UTC
Images served from 
   /owf/images 
are mapped by /images in UrlMappings and get routed to getImageURL(). This method cannot seem to locate the image file from a theme located in the external classpath location. This is likely happening because the resource lookup used in ThemeService.getImageURL() is failing in some cases.

Quick test: move a bundled theme out to the external classpath location, default is tomcat/lib/themes, replace the images/brand-logo.png with some other image, and test by loading the About popup in OWF.  The about.jsp page loads the image using a straight IMG request rooted at /owf/images and should fail to load the image. Move theme back under internal webapps/owf/themes are to see it succeed.

Known workarounds:
* move the entire theme down under the internal webapps/owf/themes area 
* copy the theme/images images down under internal common location webapps/owf/themes/common/images

**Comment by rpokorny** [comment] 2016-06-29 20:24
Unable to reproduce at this point in time.  Closing.

**Closed by rpokorny** 2016-06-29 20:24 UTC
