### ISSUE TITLE
Automatic Group Assignment not Working OWF 7.17

### ISSUE THREAD

**Issue by DTalpas** [ozoneplatform/owf-framework#83] opened 2016-10-12 16:02 UTC
Here are the steps to recreate the issue regarding automatic group assignment failing to work as it did in OWF 7.16:

1)  Download and unzip the OWF 7.17 bundle

2)  Open the apache-tomcat/lib/users.properties file in an editor

3)  Duplicate the testAdmin1 line and create a user with the login ID testAdmin2, display name of "Test Admin 2", email testAdmin2@nowhere.com.  

4)  Rename "group3" on the end of the testAdmin2 line to "group7" and also change the description and email address for group7 accordingly.  Save changes and exit the editor.

5)  Start OWF.

6)  Open a web browser and connect to OWF.  Log in as testAdmin2.

7)  Click "My Apps" and open the "Users and Groups" widget.  

8)  Check that the user testAdmin2 has been added to the user list.  Check that "group7" has been added to the group list.  Both of these checks should be successful.

9)  Double-click the testAdmin2 user record to open the user editor and select the "Groups" button/tab.  Confirm that testAdmin2 has NOT been automatically assigned to be a member of group7, this is the issue.

**Comment by rpokorny** [comment] 2016-10-12 18:48
This sounds like a duplicate of #73.  Please try building OWF from master to determine if you still see the issue there.

**Closed by rpokorny** 2016-10-12 18:48 UTC
