### ISSUE TITLE
OWF ToolBar is not showing up

### ISSUE THREAD

**Issue by buutran** [ozoneplatform/owf-framework#17] opened 2013-05-03 15:57 UTC
Hello Experts,
I am so new to OWF. I installed OWF with localhost option and connect to database, it worked fine. But after changing the localhost to servername (generated server certs and user cert by following the instruction). I was able to login to servername:8443/owf/ by testAdmin1/password but OWF ToolBar wont show up any more! Please Help
Thanks so much

**Comment by rpokorny** [comment] 2016-06-29 20:42
Most likely either a configuration issue or a duplicate of #25.  Closing.

**Closed by rpokorny** 2016-06-29 20:42 UTC
Labels: question
